# Generated by Django 4.1.4 on 2022-12-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_laptop_delete_refri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('peso', models.CharField(max_length=50)),
                ('modelo_cpu', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('peso', models.CharField(max_length=50)),
                ('min_temperatura', models.CharField(max_length=50)),
                ('smart_screen', models.CharField(max_length=50)),
                ('volumen', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
